apiVersion: v1
kind: Pod
metadata:
  name: emptydir
  labels:
    app: emptydir
spec:
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - mountPath: /cache
          name: cont-store
    - name: cont2
      image: busybox
      command: ["sh", "-c", "sleep 600"]
      volumeMounts:
        - mountPath: /cache@busybox
          name: cont-store

  volumes:
    - name: cont-store
      emptyDir: {}
