apiVersion: v1
kind: Pod
metadata:
  name: hostpath
  labels:
    app: hostpath
spec:
  containers:
    - name: host
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: hostcont
  volumes:
    - name: hostcont
      hostPath:
        path: /data
        type: DirectoryOrCreate
    
